<a href="https://colab.research.google.com/github/kartk/ML/blob/main/Decision_Trees_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from typing import List, Tuple

# *Creating Data*

1)  For a given value of k, m, (number of features, number of data points), write a function to generate a trainingdata set based on the above scheme.

In [211]:
class Node:
  def __init__(self, data):
    self.left = None
    self.right = None
    self.data = data
  def pretty_print(self):
      print_tree(self,nameattr="data")


class DecisionTree:
  def __init__(self, k:int, m:int )-> None:
    self.data = self.datagenerator(k,m)
    self.tree = None
  def datagenerator(self, k:int, m:int)->List[List[int]]:
    """
    Input:
      k: number of features
      m: number of data points
    Returns:
      Numpy array of size (m,k)
    """
    data = []
    w_den = sum([np.power(0.9, i) for i in range(2, k+1)])
    for i in range(m):
      X = [np.random.choice([1,0], p=[0.5, 0.5])]
      for j in range(1,k):
        X.append(np.random.choice([X[j-1], 1-X[j-1]], p = [0.75, 0.25]))
      X.append(X[1] if (sum([ np.power(0.9, j)/w_den * X_j for j, X_j in enumerate(X[1:])]) >= 0.5) else (1 - X[1]))
      data.append(X)
    return np.array(data)

  def entropy(self, vector:np.array)->np.array:
    P_0 = (vector == 0).sum(0) / len(vector)
    P_1 = (vector == 1).sum(0) / len(vector)
    H_Y = - P_0 * np.log2(P_0) - P_1 * np.log2(P_1)
    return H_Y

  def fit(self, data):
    # print(data)
    X, Y = data[:,:-1], data[:,-1]
    if ((Y == 0).sum(0) == len(Y) or (Y == 1).sum(0) == len(Y)):
      print("returning")
      return Node("Y=0") if (Y == 0).sum(0) == len(Y) else Node("Y=1")
    # Calculating H(Y)
    H_Y = self.entropy(Y)

    # # Calculating H(Y|X)
    cond_X_Y = []
    for i in range(X.shape[1]):
      P_X_0 = (X[:,i] == 0).sum(0) / len(X[:,i])
      P_X_1 = (X[:,i] == 1).sum(0) / len(X[:,i])
      # print(Y[np.where(X[:,i]==0)])
      # print(Y[np.where(X[:,i]==1)])
      H_Y_X_0 = max(0, self.entropy(Y[np.where(X[:,i]==0)]))
      H_Y_X_1 = max(0, self.entropy(Y[np.where(X[:,i]==1)]))
      # print(f"{i} {H_Y_X_0} {H_Y_X_1}")
      cond_X_Y.append(P_X_0 * H_Y_X_0 + P_X_1 * H_Y_X_1)
    IG = H_Y - cond_X_Y
    print(IG)
    # print(H_Y)
    # print(cond_X_Y)
    # print(IG)
    max_IG = np.argmax(IG)
    print(max_IG)
    print()
    print("fitting 0")
    node = Node(max_IG)
    node.left = self.fit(data[np.where(data[:,max_IG] == 0)])
    print("fitting 1")
    node.right = self.fit(data[np.where(data[:,max_IG] == 1)])
    return node
  def train(self):
    self.tree=self.fit(self.data)



In [218]:
dt = DecisionTree(3, 8)

In [220]:
dt.train()

[0.204434   0.12255625 0.46691719]
2

fitting 0
returning
fitting 1
[0.91829583 0.91829583 0.        ]
0

fitting 0
returning
fitting 1
returning


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: divide by zero encountered in log2
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in long_scalars


In [219]:
dt.data

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 1]])

In [221]:
dt.tree.pretty_print()

  ┌Y=1
 2┤
  | ┌Y=0
  └0┤
    └Y=1


In [ ]:
data = datagenerator(k=4, m =30)

In [ ]:
def entropy(vector):
  P_0 = (vector == 0).sum(0) / len(vector)
  P_1 = (vector == 1).sum(0) / len(vector)
  H_Y = - P_0 * np.log2(P_0) - P_1 * np.log2(P_1)
  return H_Y

In [ ]:
def fit(data):
  print(data)
  X, Y = data[:,:-1], data[:,-1]
  if ((Y == 0).sum(0) == len(Y) or (Y == 1).sum(0) == len(Y)):
    print("returning")
    return
  # Calculating H(Y)
  H_Y = entropy(Y)

  # # Calculating H(Y|X)
  cond_X_Y = []
  for i in range(X.shape[1]):
    P_X_0 = (X[:,i] == 0).sum(0) / len(X[:,i])
    P_X_1 = (X[:,i] == 1).sum(0) / len(X[:,i])
    

    # print(Y[np.where(X[:,i]==0)])
    # print(Y[np.where(X[:,i]==1)])


    H_Y_X_0 = max(0, entropy(Y[np.where(X[:,i]==0)]))
    H_Y_X_1 = max(0, entropy(Y[np.where(X[:,i]==1)]))
    # print(f"{i} {H_Y_X_0} {H_Y_X_1}")
    cond_X_Y.append(P_X_0 * H_Y_X_0 + P_X_1 * H_Y_X_1)


  IG = H_Y - cond_X_Y
  print(H_Y)
  print(cond_X_Y)
  print(IG)

  max_IG = np.argmax(IG)
  print(max_IG)
  print()
  print("fitting 0")
  fit(data[np.where(data[:,max_IG] == 0)])
  print("fitting 1")
  fit(data[np.where(data[:,max_IG] == 1)])



In [ ]:
fit(data)

[[0 1 1 1 1]
 [0 0 1 0 1]
 [0 0 0 0 1]
 [1 1 0 1 1]
 [0 1 1 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [1 0 0 0 1]
 [0 0 1 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [0 0 0 1 1]
 [0 0 1 1 0]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 0]
 [0 1 0 1 1]
 [0 0 1 1 0]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 1 1]]
0.5665095065529053
[0.5468627893834475, 0.5665095065529053, 0.5665095065529053, 0.5660149997115376]
[0.01964672 0.         0.         0.00049451]
0

fitting 0
[[0 1 1 1 1]
 [0 0 1 0 1]
 [0 0 0 0 1]
 [0 1 1 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 1 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [0 0 0 1 1]
 [0 0 1 1 0]
 [0 0 0 0 1]
 [0 1 0 1 1]
 [0 0 1 1 0]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 1 1]]
0.4537163391869448
[0.4537163391869448, 0.394448519054885, 0.3437752832796963, 0.3437752832796963]
[0.         0.05926782 0.10994106 0.10994106]
2

fitting 0
[[0 0 0 0 1]
 [0 0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in long_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log2
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.


In [ ]:
IG = [0.02244831, 0.03082069, 0.00061424, 0.02966723]

In [ ]:
np.argmax(IG)

1

In [ ]:
!pip install pptree

  Created wheel for pptree: filename=pptree-3.1-cp36-none-any.whl size=4632 sha256=2ae25809d1fd5378ab123bd5e0801c350af937dcc6cc8453d9df8d1a775f1aa9
  Stored in directory: /root/.cache/pip/wheels/ff/bf/ee/8b67eb5467e12cf1bd0125df70d8c9f076bd7ea225b5bcea9b
Successfully built pptree


In [ ]:
from ppbtree import print_tree

In [ ]:
print_tree(node, nameattr="data")

      ┌Y=1
    ┌1┤
    | └Y=0
  ┌2┤
  | |   ┌Y=1
  | | ┌3┤
  | | | └Y=0
  | └1┤
  |   └Y=1
 0┤
  |   ┌Y=1
  | ┌1┤
  | | | ┌Y=0
  | | └3┤
  | |   └Y=1
  └2┤
    └Y=1
